server:
  port: 7000
  servlet:
    session.timeout: 300

logging:
  level:
    org.springframework.web: DEBUG


spring:
  #Druid
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://66.42.68.168:3306/ssodemo?useSSL=false
    username: root
    password: 11111

  #Thymeleaf
  thymeleaf:
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
    template-resolver-order: 0
    cache: false

  #redis
  redis:
      cluster:
        nodes: 44.99.215.55:18175,44.99.215.55:18176,44.99.215.55:18177
        max-redirects: 6
      timeout: 300000
      jedis:
        pool:
          max-active: 8
          max-wait: 100000
          max-idle: 8
          min-idle: 0

#mybatis
mybatis:
  type-aliases-package: cn.zifangsky.mapper
  mapper-locations: classpath:cn/xhjc/mapper/xml/*.xml